/* Generated By:JavaCC: Do not edit this line. ProcessParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ProcessParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DATASET = 3;
  /** RegularExpression Id. */
  int LC = 4;
  /** RegularExpression Id. */
  int RC = 5;
  /** RegularExpression Id. */
  int COM = 6;
  /** RegularExpression Id. */
  int NL = 7;
  /** RegularExpression Id. */
  int SM = 8;
  /** RegularExpression Id. */
  int EQ = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int IDENTIFIERS = 11;
  /** RegularExpression Id. */
  int SPACE = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\" \\r\"",
    "\"DataSet\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"\\n\"",
    "\";\"",
    "\"=\"",
    "\"String\"",
    "<IDENTIFIERS>",
    "<SPACE>",
  };

}
