/* Generated By:JavaCC: Do not edit this line. ProcessParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ProcessParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LC = 6;
  /** RegularExpression Id. */
  int RC = 7;
  /** RegularExpression Id. */
  int COM = 8;
  /** RegularExpression Id. */
  int SM = 9;
  /** RegularExpression Id. */
  int EQ = 10;
  /** RegularExpression Id. */
  int WQ = 11;
  /** RegularExpression Id. */
  int STRING = 12;
  /** RegularExpression Id. */
  int DATASET = 13;
  /** RegularExpression Id. */
  int GRAPH = 14;
  /** RegularExpression Id. */
  int DB = 15;
  /** RegularExpression Id. */
  int IDENTIFIERS = 16;
  /** RegularExpression Id. */
  int STR = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\f\"",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "\"=\"",
    "\"\\\"\"",
    "\"String\"",
    "\"DataSet\"",
    "\"Graph\"",
    "\"DB\"",
    "<IDENTIFIERS>",
    "<STR>",
  };

}
